version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=mydb
    depends_on:
      - postgres_db
    volumes:
      - ./:/app
      - /app/node_modules

  client:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3001:3000"  # React se sirve en http://localhost:3001
    command: sh -c "npm install && npm start"
    depends_on:
      - app

  postgres_db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres_db

volumes:
  postgres_data:
  pgadmin_data:
