services:
  postgres_db:                          
    image: postgres:16
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=paes
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:                       
      test: ["CMD-SHELL", "pg_isready -U postgres -d paes"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: backend
    ports:
      - "4000:4000"
    environment:
      - PGHOST=postgres_db            
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=paes
      - PORT=4000
    depends_on:
      postgres_db:
        condition: service_healthy      

  client:
    build:
      context: ./client
    container_name: client
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  dbdata:
